apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    name: rabbitmqtt
spec:
  ports:
  - port: 1883
    name: mqtt
  - port: 8883
    name: mqttssl
  - port: 15672
    name: admin
  selector:
    app: rabbitmqtt
  externalTrafficPolicy: Local
  type: LoadBalancer