apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: mqtt
  labels:
    name: rabbitmqtt
spec:
  ports:
  - port: 1883
    name: mqtt
    protocol: TCP
    targetPort: mqtt
  - port: 8883
    name: mqttssl
    protocol: TCP
    targetPort: mqttssl
  - port: 15672
    name: rabbitmqadmin
    protocol: TCP
    targetPort: rabbitmqadmin
  selector:
    app: rabbitmqtt
  type: LoadBalancer