apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-rabbitmq
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alertmanager-discovery
subjects:
- kind: ServiceAccount
  name: prometheus-rabbitmq
  namespace: mqtt
