apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-rabbitmq
  namespace: mqtt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-rabbitmq
subjects:
- kind: ServiceAccount
  name: prometheus-rabbitmq
  namespace: mqtt
